/**
 * Link validation.
 *
 * Release plan step 5. Checks every destination the site offers a visitor:
 * external URLs are requested, mailto: links are parsed, and local asset paths
 * are resolved against public/ or against the App Router route that generates
 * them.
 *
 * Exits non-zero when a publicly visible link is broken (NFAC-TEST-001). Links
 * that only exist in Draft content are reported as pending rather than failing
 * — see the isPublic note in src/domain/content/link-validation.ts.
 *
 * This command needs network access. A link checker that passes while offline
 * would be worse than no link checker, so a request that cannot be made is
 * reported as a failure rather than skipped.
 */

import { existsSync } from "node:fs";

import { aiPractices } from "@/content/ai-practices";
import { contactChannels, externalProfiles } from "@/content/contact";
import { experience } from "@/content/experience";
import { mediaAssets } from "@/content/media";
import { profile } from "@/content/profile";
import { projects } from "@/content/projects";
import { resume } from "@/content/resume";
import { siteConfig } from "@/content/site";
import { skills } from "@/content/skills";
import type { LinkTarget } from "@/domain/content/link-validation";
import {
  classifyExternalStatus,
  collectLinks,
  emailAddressOf,
  localAssetCandidates,
} from "@/domain/content/link-validation";

const REQUEST_TIMEOUT_MS = 15_000;

type Outcome = "ok" | "manual" | "pending" | "broken";

interface Result {
  readonly target: LinkTarget;
  readonly outcome: Outcome;
  readonly detail: string;
}

/**
 * Request a URL, preferring HEAD.
 *
 * Some hosts reject HEAD outright, so a 405 or 501 is retried as GET before the
 * link is judged. Without the retry a working destination reads as broken.
 */
async function requestStatus(url: string): Promise<number | Error> {
  const attempt = async (method: "HEAD" | "GET"): Promise<Response> =>
    fetch(url, {
      method,
      redirect: "follow",
      signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      headers: {
        // Identify honestly. Sending a browser user agent to slip past an
        // anti-bot check would make the result a lie about what a visitor sees.
        "user-agent": "developer-portfolio-link-check",
        accept: "*/*",
      },
    });

  try {
    const response = await attempt("HEAD");

    if (response.status === 405 || response.status === 501) {
      return (await attempt("GET")).status;
    }

    return response.status;
  } catch (error) {
    return error instanceof Error ? error : new Error(String(error));
  }
}

function checkLocalAsset(target: LinkTarget): Result {
  const { publicFile, routeFiles } = localAssetCandidates(target.value);

  if (existsSync(publicFile)) {
    return { target, outcome: "ok", detail: `served from ${publicFile}` };
  }

  const route = routeFiles.find((candidate) => existsSync(candidate));

  if (route !== undefined) {
    return { target, outcome: "ok", detail: `generated by ${route}` };
  }

  if (!target.isPublic) {
    return { target, outcome: "pending", detail: "no file yet, and not publicly visible" };
  }

  return {
    target,
    outcome: "broken",
    detail: `no file at ${publicFile} and no route generating it`,
  };
}

function checkEmail(target: LinkTarget): Result {
  const address = emailAddressOf(target.value);

  if (address === null) {
    return { target, outcome: "broken", detail: "not a usable mailto: address" };
  }

  // Deliverability cannot be checked without sending mail, which this must not
  // do. The release checklist requires the address be confirmed by hand.
  return { target, outcome: target.isPublic ? "manual" : "pending", detail: address };
}

async function checkExternal(target: LinkTarget): Promise<Result> {
  const status = await requestStatus(target.value);

  if (status instanceof Error) {
    return {
      target,
      outcome: target.isPublic ? "broken" : "pending",
      detail: `request failed: ${status.message}`,
    };
  }

  const verdict = classifyExternalStatus(target.value, status);

  if (verdict === "reachable") {
    return { target, outcome: "ok", detail: `HTTP ${status}` };
  }

  if (verdict === "requires-manual-check") {
    return {
      target,
      outcome: "manual",
      detail: `HTTP ${status} — anti-bot challenge, not a statement about the resource`,
    };
  }

  return {
    target,
    outcome: target.isPublic ? "broken" : "pending",
    detail: `HTTP ${status}`,
  };
}

const HEADINGS: Record<LinkTarget["kind"], string> = {
  external: "External destinations",
  email: "Email",
  "local-asset": "Local assets",
};

const MARKERS: Record<Outcome, string> = {
  ok: "ok     ",
  manual: "manual ",
  pending: "pending",
  broken: "BROKEN ",
};

function report(results: readonly Result[]): void {
  console.log("Link validation\n");

  for (const kind of ["external", "email", "local-asset"] as const) {
    const group = results.filter((result) => result.target.kind === kind);

    if (group.length === 0) continue;

    console.log(`  ${HEADINGS[kind]}`);

    for (const { target, outcome, detail } of group) {
      console.log(`    ${MARKERS[outcome]}  ${target.value}`);
      console.log(`             ${detail}`);

      if (outcome === "broken" || outcome === "manual") {
        for (const source of target.sources) {
          console.log(`             via ${source}`);
        }
      }
    }

    console.log("");
  }
}

async function main(): Promise<void> {
  const targets = collectLinks(
    {
      profile,
      experience,
      projects,
      skills,
      aiPractices,
      resumes: [resume],
      contactChannels,
      externalProfiles,
      mediaAssets,
    },
    siteConfig,
  );

  const results = await Promise.all(
    targets.map(async (target): Promise<Result> => {
      if (target.kind === "local-asset") return checkLocalAsset(target);
      if (target.kind === "email") return checkEmail(target);
      return checkExternal(target);
    }),
  );

  report(results);

  const broken = results.filter((result) => result.outcome === "broken");
  const manual = results.filter((result) => result.outcome === "manual");
  const pending = results.filter((result) => result.outcome === "pending");

  if (pending.length > 0) {
    console.log(
      `${pending.length} link(s) pending: authored in content that is not public yet, ` +
        `so an absent target is expected rather than broken.`,
    );
  }

  if (manual.length > 0) {
    console.log(
      `${manual.length} link(s) need a human. An automated request cannot confirm these; ` +
        `open each one and confirm it resolves to the approved destination ` +
        `(docs/release-checklist.md step 5).`,
    );
  }

  if (broken.length > 0) {
    console.error(`\n${broken.length} publicly visible link(s) are broken.`);
    process.exit(1);
  }

  console.log("\nNo publicly visible link is broken.");
}

main().catch((error: unknown) => {
  // An unexpected rejection must fail the gate. Letting it surface as an
  // unhandled warning would leave the command reporting success.
  console.error("Link validation could not complete.");
  console.error(error);
  process.exit(1);
});
